### ISSUE TITLE
can't install role from ansible-galaxy

### ISSUE THREAD

**Issue by pkubica** [oVirt/ovirt-ansible-vm-infra#10]
$ ansible-galaxy install oVirt.vm-infra -vvv
ansible-galaxy 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/pkubica/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Using /etc/ansible/ansible.cfg as config file
Opened /home/pkubica/.ansible_galaxy
Processing role oVirt.vm-infra 
Opened /home/pkubica/.ansible_galaxy
- downloading role 'vm-infra', owned by oVirt
https://galaxy.ansible.com/api/v1/roles/?owner__username=oVirt&name=vm-infra
https://galaxy.ansible.com/api/v1/roles/22433/versions/?page_size=50
- downloading role from https://github.com/oVirt/ovirt-ansible-vm-infra/archive/1.1.3.tar.gz
- extracting oVirt.vm-infra to /etc/ansible/roles/oVirt.vm-infra
- extracting oVirt.vm-infra to /usr/share/ansible/roles/oVirt.vm-infra
ERROR! Unexpected Exception, this is probably a bug: list index out of range
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 106, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 150, in run
    self.execute()
  File "/usr/lib/python2.7/site-packages/ansible/cli/__init__.py", line 155, in execute
    fn()
  File "/usr/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 393, in execute_install
    installed = role.install()
  File "/usr/lib/python2.7/site-packages/ansible/galaxy/role.py", line 332, in install
    self.path = self.paths[nextidx]
IndexError: list index out of range

**Comment by pkubica** [comment]
it caused by this bug:
https://github.com/ansible/galaxy/issues/149

**Comment by pkubica** [comment]
to solve this: up to version of ansible 2.5 use ansible-galaxy with sudo
fix: https://github.com/ansible/ansible/pull/32627
