### ISSUE TITLE
Wait_for_IP gives up too soon

### ISSUE THREAD

**Issue by cwilkers** [oVirt/ovirt-ansible-vm-infra#34]
When specifying wait_for_ip: true, the code which queries the engine for IPs returns as soon as any IP is reported. The first IP to come available in most (el7) VMs on first run is an IPV6 self-assigned address, e.g.
```
[{u'ips': [{u'version': u'v6', u'address': u'fe80::21a:4aff:fe16:201'}]
```
I would like to be able to request either an IPv4 address, or at least not be satisfied with an `fe80::`.

**Comment by cwilkers** [comment]
This code might work for the IPv4 case.
```
    query: "reported_devices[*].ips[?version='v4'].address"
```

**Comment by cwilkers** [comment]
It looks like this is still an issue with the latest commit.

I'm getting failures adding hosts now in the `create_inventory.yml` tasks when some of the VMs come up with fe80 IPv6 IPs.

I see `creating host via 'add_host': hostname=[]` in the debug output.

```
ERROR! Unexpected Exception, this is probably a bug: unhashable type: 'list'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 118, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 159, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 289, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 321, in run
    results += self._wait_on_pending_results(iterator)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 674, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 117, in inner
    results = func(self, iterator, one_pass=one_pass, max_passes=max_passes)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 582, in _process_pending_results
    self._add_host(new_host_info, iterator)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 692, in _add_host
    if host_name not in self._inventory.hosts:
TypeError: unhashable type: 'list'
```
